#include <iostream>
#include "ArrayBag.h"

using namespace std;
int main() {
    int size , freq;
    bool contain , empty;
    ArrayBag arrayBag;
    empty = arrayBag.isEmpty();
    cout << "Empty : "<< empty << endl;
    size = arrayBag.getCurrentSize();
    cout <<"Size : "<< size << endl;
    arrayBag.add(4);
    arrayBag.add(1);
    arrayBag.add(6);
    size = arrayBag.getCurrentSize();
    cout <<"Size : "<< size << endl;
    arrayBag.printArray();
    arrayBag.remove(5);
    size = arrayBag.getCurrentSize();
    cout <<"Size : "<< size << endl;
    arrayBag.printArray();
    arrayBag.remove(4);
    size = arrayBag.getCurrentSize();
    cout <<"Size : "<< size << endl;
    arrayBag.printArray();
    contain = arrayBag.contains(1);
    cout << "Contain 1 : "<< contain << endl;
    arrayBag.remove(1);
    contain = arrayBag.contains(1);
    cout << "Contain 1 : "<< contain << endl;
    size = arrayBag.getCurrentSize();
    cout <<"Size : "<< size << endl;
    arrayBag.printArray();
    empty = arrayBag.isEmpty();
    cout << "Empty : "<< empty << endl;
    arrayBag.add(10);
    arrayBag.add(20);
    arrayBag.add(-58);
    freq = arrayBag.getFreqOf(20);
    cout << "Freq 20 : "<< freq << endl;
    arrayBag.printArray();
    arrayBag.add(20);
    freq = arrayBag.getFreqOf(20);
    cout << "Freq 20 : "<< freq << endl;
    arrayBag.clear();
    size = arrayBag.getCurrentSize();
    cout <<"Size : "<< size << endl;
    arrayBag.printArray();
    arrayBag.add(3);
    arrayBag.add(3);
    arrayBag.add(1);
    arrayBag.add(3);
    arrayBag.add(8);
    arrayBag.add(6);
    arrayBag.printArray();
    arrayBag.reverseArray();
    cout << "After reverse function : "<< endl;
    arrayBag.printArray();
    arrayBag.allFreq();
    arrayBag.removeAll(0);
    arrayBag.removeAll(3);
    cout << "After remove all 3's and 0's : "<< endl;
    arrayBag.printArray();
    arrayBag.remainEven();
    cout << "After remainEven funct. : "<< endl;
    arrayBag.printArray();
    arrayBag.add(13);
    arrayBag.add(18);
    arrayBag.add(17);
    arrayBag.add(19);
    cout << "After adding some elements : "<<endl;
    arrayBag.printArray();
    arrayBag.remainOdd();
    cout << "After remainOdd func. : "<< endl;
    arrayBag.printArray();
    return 0;
}
